### ISSUE TITLE
Problem with ember-cli-compass-compiler and ember-basic-dropdown

### ISSUE THREAD

**Issue by Haidy777** [cibernox/ember-basic-dropdown#119]
If I'm starting a new ember-app with both I get an interesting error.

```
Serving on http://localhost:4200/
directory tmp/compass_compiler-output_path-sDmbDsmx.tmp/assets/
   create tmp/compass_compiler-output_path-sDmbDsmx.tmp/assets/app.css
    error tmp/compass_compiler-input_base_path-5niakTBe.tmp/0/app/styles/ember-basic-dropdown.scss (Line 16: Invalid CSS
 after "  &-": expected number or function, was "-left { left: 0; }")
   create tmp/compass_compiler-output_path-sDmbDsmx.tmp/assets/ember-basic-dropdown.css

The Broccoli Plugin: [CompassCompiler] failed with:
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "compass compile --output-style=compressed --sass-dir=E:/GitHub
/dropdown-test/tmp/compass_compiler-input_base_path-5niakTBe.tmp/0/app/styles --css-dir="E:\GitHub\dropdown-test\tmp\com
pass_compiler-output_path-sDmbDsmx.tmp\assets""

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:486:12)

The broccoli plugin was instantiated at:
    at CompassCompiler.Plugin (E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\node_modules\broccoli-com
pass-compiler\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\index.js:10:31)
    at CompassCompiler.CachingWriter [as constructor] (E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\n
ode_modules\broccoli-compass-compiler\node_modules\broccoli-caching-writer\index.js:21:10)
    at new CompassCompiler (E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\node_modules\broccoli-compas
s-compiler\lib\compiler.js:17:17)
    at CompassCompiler (E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\node_modules\broccoli-compass-co
mpiler\lib\compiler.js:10:52)
    at E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\index.js:67:23
    at Array.map (native)
    at CompassCompilerPlugin.toTree (E:\GitHub\dropdown-test\node_modules\ember-cli-compass-compiler\index.js:38:40)
    at E:\GitHub\dropdown-test\node_modules\ember-cli\node_modules\ember-cli-preprocess-registry\preprocessors.js:184:26

    at Array.forEach (native)
    at processPlugins (E:\GitHub\dropdown-test\node_modules\ember-cli\node_modules\ember-cli-preprocess-registry\preproc
essors.js:182:11)
```

Interestingly this isn't a problem with older versions of "ember-cli-compass-compiler".
To reproduce I set up a simple github repo (https://github.com/Haidy777/dropdown-test).

The master shows the problem with ```ember-power-select``` and the ```basic-dropdown```-branch shows the error with ```ember-basic-dropdown```.
Since it seems like something with ```ember-basic-dropdown``` I thought I open the issue here and not at ```ember-power-select```.

**Comment by cibernox** [comment]
The only "officially supported" sass compiler is is `ember-cli-sass`, but i'd expect that an app using any other sass compiler to just include the compiled stylesheet like if no sass plugin is found.

I'll check it.

**Comment by cibernox** [comment]
Ok, I've found the problem.

Apparently ember-cli-compass-compiler doesn't support this syntax:

```
  &--left { left: 0; }
  &--right { right: 0; }
```

Which is perfectly valid syntax in sass. I guess that it has fallen behind in features.

I've just fixed it but this will still leave you with one problem. Probably you added `@import 'ember-power-select';` somewhere. However, unless you are using `ember-cli-sass`, the addon is going to import the compiled styles.

If you do that, you're going to end up with the styles included twice, once in `vendor` and another in `my-app.scss`. You can tell the addon to not include any EPS theme with the `theme: false` configuration option: http://www.ember-power-select.com/cookbook/bootstrap-theme (at the bottom)
