### ISSUE TITLE
removeEventListener exception on IE 11

### ISSUE THREAD

**Issue by Kilowhisky** [cibernox/ember-basic-dropdown#130]
Get this error when navigating away from a route with a dropdown in IE 11 when i have the developer tools open and i run a production build. Can't be sure it happens when the tools are closed and it doesn't happen when using a development build.  

Dropdown declaration. 

```
{{#power-select-multiple renderInPlace=true options=assets selected=filteredAssets searchField="name" placeholder=(t 'track.trackEventsChooseAssetsToShow') onchange=(action "assetFilterChanged") as |asset|}}
              {{icon-asset asset=asset class="text-bottom" width="20px" height="20px"}}
              {{asset.name}}
              {{#if asset.registration}}<div class="description">({{asset.registration}})</div>{{/if}}
{{/power-select-multiple}}
```
Stack Trace
```
"TypeError: Unable to get property 'removeEventListener' of undefined or null reference
   at removeGlobalEvents (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:34:23452)
   at _teardown (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:34:24415)
   at willDestroyElement (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:34:20486)
   at r (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:11:30486)
   at trigger (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:16:814)
   at r (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:11:30486)
   at d.prototype.willDestroyElement (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:9:10395)
   at d.prototype.remove (https://myapp/assets/vendor-d42d5df2bd86ce26959f3ab73da5b5bd.js:"
```

**Comment by cibernox** [comment]
That is weird, because looking at the stack trace seems that this error comes from `removeGlobalEvents`, and in that method the events are being removed from `window`. There is no way that window can be undefined 😲

**Comment by cibernox** [comment]
Oh, I see that this method does remove events from `dropdownElement`. However that's only the case if the browser doesn't support mutation observer. IE11 supports MutationObserver, according to can-i-use.

**Comment by Kilowhisky** [comment]
Bingo. It was in IE 10 emulation mode. (D'oh) Any chance for a work around for this? My app explicitly supports IE 10 right now.

**Comment by Kilowhisky** [comment]
Would this be a suitable polyfill? I can load this in on my own. 

https://github.com/megawac/MutationObserver.js?files=1

**Comment by cibernox** [comment]
I already fallback to DOM-Events if MutationObserver is not supported. By in one refactor I must have break that, and admittedly I don't have CI for IE, it's very easy to break things in IE.

I'll investigate, but not until ~15th of August 🏄 ⛵ ☀️ 🌊

**Comment by Kilowhisky** [comment]
Polyfill doesn't appear to work quite right. Any suggestions while its being worked on? This is blocking me from jumping to 2.7.0

**Comment by jdurand** [comment]
Just bumped into this in production (beta) from a IE10 client.
I'm logging this here: 
```
/version: 2.0.0-beta.8+→
/language: fr-CA→
/account: 20b231622168778 – AMC →
/restaurant: LND014725012761→
user-agent: Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)→
/modern-browser: yes→
/TypeError: Unable to get property 'removeEventListener' of undefined or null reference→
at removeGlobalEvents (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:28:30515)→
at _teardown (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:28:31450)→
at willDestroyElement (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:28:27520)→
at r (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:13:4412)→
at trigger (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:17:7013)→
at r (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:13:4412)→
at willDestroyElement (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:10:16830)→
at remove (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:10:16381)→
at destroyElement (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:17:9929)→
at cleanup (https://widgets.libroreserve.com/booking/assets/vendor-16988bbe7aa17cdb25e993404251f424.js:17:9867)→
```

**Comment by jdurand** [comment]
@cibernox how can `self.window`ever be nil here? https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L179

**Comment by cibernox** [comment]
@jdurand No idea, unless we are talking about fastboot.

**Comment by cibernox** [comment]
I've just tried removing `self` everywhere. I've just read about some problems with `self` in IE10.

@jdurand Can you try this branch? https://github.com/cibernox/ember-basic-dropdown/pull/144/

**Comment by jdurand** [comment]
Ok, so i debugged this and it turns out that `this.dropdownElement` is nil on IE 10 (https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L188)
Wrapping this block fixes (patches) the issue...
````
if (this.dropdownElement) {
  this.dropdownElement.removeEventListener('DOMNodeInserted', this.runloopAwareReposition);
  this.dropdownElement.removeEventListener('DOMNodeRemoved', this.runloopAwareReposition);
}
````

**Comment by cibernox** [comment]
Ok, I'll get a VM to debug this at some point today.

**Comment by Kilowhisky** [comment]
It appears to be because `_teardown()` is being called when the component is destroyed.

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L70

But `this.dropdownElement` is only assigned when the dropdown is opened and then set back to `null` when the dropdown is closed. 

https://github.com/cibernox/ember-basic-dropdown/blob/master/addon/components/basic-dropdown/content.js#L138

So it looks like @jdurand 's answer is correct. It shouldn't even be trying to call those lines because the element has either already been cleared by `close` or it was never assigned because the box was never opened. 

Want a PR?

**Comment by cibernox** [comment]
If you already know the fix, please, go ahead.

**Comment by jdurand** [comment]
@Kilowhisky can you check if https://github.com/cibernox/ember-basic-dropdown/pull/145 fixes your issue?

**Comment by Kilowhisky** [comment]
Yea that'll fix it. Though I'm not sure the method even needs to be called on willdestroy(). Didn't check that case though. 

Good enough for me!
