### ISSUE TITLE
Test helper `clickTrigger` does not work in IE

### ISSUE THREAD

**Issue by anehx** [cibernox/ember-basic-dropdown#243]
I wrote my tests using your helper `clickTrigger`. When testing in IE, I get the following error message:
```
TypeError: Object doesn't support this action
  at nativeClick (http://localhost:7357/assets/tests.js:1112:5)
  at clickTrigger (http://localhost:7357/assets/tests.js:1145:5)
  at Anonymous function (http://localhost:7357/assets/tests.js:1943:8)
  at invoke (http://localhost:7357/assets/test-support.js:13227:5)
  at method (http://localhost:7357/assets/test-support.js:13292:13)
  at callFnAsync (http://localhost:7357/assets/test-support.js:4500:5)
  at Runnable.prototype.run (http://localhost:7357/assets/test-support.js:4452:7)
  at Runner.prototype.runTest (http://localhost:7357/assets/test-support.js:4940:5)
  at Anonymous function (http://localhost:7357/assets/test-support.js:5046:7)
  at next (http://localhost:7357/assets/test-support.js:4860:7)
```
Tested in IE11 via SauceLabs

**Comment by anehx** [comment]
PhantomJS fails too:
```
TypeError: '[object EventConstructor]' is not a constructor (evaluating 'new window.Event('mousedown', { bubbles: true, cancelable: true, view: window })')
  at nativeClick (http://localhost:7357/assets/tests.js:1112)
  at clickTrigger (http://localhost:7357/assets/tests.js:1140)
  at http://localhost:7357/assets/tests.js:1938
  at invoke (http://localhost:7357/assets/test-support.js:13227)
  at http://localhost:7357/assets/test-support.js:13292
  at callFnAsync (http://localhost:7357/assets/test-support.js:4512)
  at http://localhost:7357/assets/test-support.js:4452
  at http://localhost:7357/assets/test-support.js:4940
  at http://localhost:7357/assets/test-support.js:5077
  at next (http://localhost:7357/assets/test-support.js:4860)
  at http://localhost:7357/assets/test-support.js:4870
  at next (http://localhost:7357/assets/test-support.js:4802)
  at http://localhost:7357/assets/test-support.js:4833
  at done (http://localhost:7357/assets/test-support.js:4438)
  at http://localhost:7357/assets/test-support.js:4511
  at complete (http://localhost:7357/assets/test-support.js:13254)
  at http://localhost:7357/assets/test-support.js:13232
  at tryCatch (http://localhost:7357/assets/vendor.js:85165)
  at invokeCallback (http://localhost:7357/assets/vendor.js:85180)
  at http://localhost:7357/assets/vendor.js:85255
  at http://localhost:7357/assets/vendor.js:65050
  at http://localhost:7357/assets/vendor.js:26979
  at http://localhost:7357/assets/vendor.js:27047
  at http://localhost:7357/assets/vendor.js:27171
  at http://localhost:7357/assets/vendor.js:27241
  at http://localhost:7357/assets/vendor.js:27807
```

**Comment by cibernox** [comment]
Phantom 2.X should work. 
What version of IE are you testing in?

**Comment by cibernox** [comment]
Nvm, I read it. Apparently `new Event` doesn't work in IE11. 

It should be too hard to fix tho. I'll flag it as a bug.

FWIW, you don't need to wait for me to fix it, you can install https://github.com/cibernox/ember-native-dom-helpers right now and use `click('.ember-power-select-trigger')` instead. I intend to deprecate the integration (not acceptance) helpers of this addon anyway in the next months.

**Comment by anehx** [comment]
@cibernox Alright thanks!

By the way: Why can't I use the "normal" approach with `$('#mytrigger').click()`?

**Comment by anehx** [comment]
PhantomJS (https://www.npmjs.com/package/phantomjs-prebuilt) installed by npm on a travis container did not work.
