### ISSUE TITLE
Element modifiers are not allowed in components

### ISSUE THREAD

**Issue by Redsandro** [cibernox/ember-basic-dropdown#532]
> Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-basic-dropdown/templates/components/basic-dropdown-content.hbs
> 
> Compile Error: Element modifiers are not allowed in components

I guess the latest version is not compatible with my `ember-source` version `3.5`.

What version do I need for this?

```
Broccoli Plugin: broccoli-persistent-filter:TemplateCompiler
ember-basic-dropdown/templates/components/basic-dropdown-content.hbs: Compile Error: Element modifiers are not allowed in components in /tmp/broccoli-1IqhK2Oeix7Xo/out-379-funnel_addon_addon_template_files_ember_basic_dropdown at broccoli-persistent-filter:TemplateCompiler
                Error: Compile Error: Element modifiers are not allowed in components
    at ComponentBlock.push (/app/node_modules/ember-source/dist/ember-template-compiler.js:1404:27)
    at JavaScriptCompiler.push (/app/node_modules/ember-source/dist/ember-template-compiler.js:1707:31)
    at JavaScriptCompiler.modifier (/app/node_modules/ember-source/dist/ember-template-compiler.js:1515:18)
    at /app/node_modules/ember-source/dist/ember-template-compiler.js:1476:31
    at Array.forEach (<anonymous>)
    at JavaScriptCompiler.process (/app/node_modules/ember-source/dist/ember-template-compiler.js:1470:26)
    at Function.JavaScriptCompiler.process (/app/node_modules/ember-source/dist/ember-template-compiler.js:1464:29)
    at Function.TemplateCompiler.compile (/app/node_modules/ember-source/dist/ember-template-compiler.js:1978:39)
    at exports.precompile (/app/node_modules/ember-source/dist/ember-template-compiler.js:2565:54)
    at Object.exports.default (/app/node_modules/ember-source/dist/ember-template-compiler.js:6230:37)
              
                    at TemplateCompiler.Plugin (/app/node_modules/broccoli-plugin/index.js:7:31)
    at new Filter (/app/node_modules/ember-basic-dropdown/node_modules/broccoli-persistent-filter/index.js:87:10)
    at new TemplateCompiler (/app/node_modules/ember-basic-dropdown/node_modules/ember-cli-htmlbars/lib/template-compiler-plugin.js:35:5)
    at Object.toTree (/app/node_modules/ember-basic-dropdown/node_modules/ember-cli-htmlbars/lib/ember-addon-main.js:87:26)
    at /app/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (<anonymous>)
    at processPlugins (/app/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/app/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
    at Class.compileTemplates (/app/node_modules/ember-cli/lib/models/addon.js:1144:33)
    at Class.compileAddon (/app/node_modules/ember-cli/lib/models/addon.js:1204:30)
              
                Error: Compile Error: Element modifiers are not allowed in components
    at ComponentBlock.push (/app/node_modules/ember-source/dist/ember-template-compiler.js:1404:27)
    at JavaScriptCompiler.push (/app/node_modules/ember-source/dist/ember-template-compiler.js:1707:31)
    at JavaScriptCompiler.modifier (/app/node_modules/ember-source/dist/ember-template-compiler.js:1515:18)
    at /app/node_modules/ember-source/dist/ember-template-compiler.js:1476:31
    at Array.forEach (<anonymous>)
    at JavaScriptCompiler.process (/app/node_modules/ember-source/dist/ember-template-compiler.js:1470:26)
    at Function.JavaScriptCompiler.process (/app/node_modules/ember-source/dist/ember-template-compiler.js:1464:29)
    at Function.TemplateCompiler.compile (/app/node_modules/ember-source/dist/ember-template-compiler.js:1978:39)
    at exports.precompile (/app/node_modules/ember-source/dist/ember-template-compiler.js:2565:54)
    at Object.exports.default (/app/node_modules/ember-source/dist/ember-template-compiler.js:6230:37)
```

**Comment by cibernox** [comment]
1.x should work.

> ### Compatibility
> Version 2.0 requires Ember 3.11 or greater Versions 1.X require Ember 2.12 or greater
